name: Emerge Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload artifact to Emerge
        uses: EmergeTools/emerge-upload-action@v1.0.2
        with:
          artifact_path: ./Wikipedia.xcarchive.zip
          emerge_api_key: ${{ secrets.EMERGE_API_KEY }}
          build_type: main # Optional, change if your workflow builds a specific type
